### ISSUE TITLE
tableview请求更多时数组暴增怎么处理，一下子从几十个到几百个

### ISSUE THREAD

**Issue by liaohengjie** [zhnnnnn/ZHNThresholdHelper#1]
兄弟，请教一下，在tableview里用ZHNThresholdHelper去请求更多数据的时候，不断的滚动会卡，而且数组的元素会从几十个一下子到几百个，这里就是卡的原因，可以指教一下么？？没有去做网络请求的时候是滚动的很流畅，可以的话加一下QQ584566770

**Comment by zhnnnnn** [comment]
加你了。。。不具体到问题不清楚为什么

**Comment by liaohengjie** [comment]
没收到好友请求啊，方便的话再加一下

**Comment by liaohengjie** [comment]
我在你的项目里加了一个网络请求，请求完成后再去刷新tableview，这是oschina的项目链接
https://git.oschina.net/iosdev_liao/preloadTest.git

**Comment by zhnnnnn** [comment]
你的qq好像需要验证。。。。我把bug修复了。。。加了个值判断是否正在请求数据。你拉一份新的代码。。你那个demo里面请求成功里面加一句[self.helper endLoadDatas];就好了。。。。你添加数据的时候最好每一次都添加相同的个数（初始化的时候是30后面最好也是30）

**Comment by liaohengjie** [comment]
好了，3q
